from collections.abc import Mapping
from typing import Protocol


class ProjectStore(Protocol):
    def save_project(self, project: Mapping[str, object]) -> dict[str, object]: ...
    def get_project(self, project_id: str) -> dict[str, object] | None: ...
    def list_projects(self) -> list[dict[str, object]]: ...


class RunStore(Protocol):
    def save_run(self, run: Mapping[str, object]) -> dict[str, object]: ...
    def get_run(self, run_id: str) -> dict[str, object] | None: ...
    def list_runs(self, project_id: str | None = None) -> list[dict[str, object]]: ...


class EventStore(Protocol):
    def append_event(self, event: Mapping[str, object]) -> dict[str, object]: ...
    def list_events(self, run_id: str) -> list[dict[str, object]]: ...


class Persistence(ProjectStore, RunStore, EventStore, Protocol):
    pass
